.gitignore, src/App.tsx, src/index.css, src/main.tsx, tailwind.config.js
- #33 
- Radix theme 루트 파일 세팅
- 기본 CSS 세팅 수정
- 
- 늦은 시간까지 함께 고생해주신 @juhee067 @davidktlee 감사합니다!
=> [B조] Radix theme 루트 파일 세팅

src/components/Common/Txt.tsx
=> [FIX] Txt 색상 적용 정상화

src/layout/root.tsx
- #43 
- RootLayout의 main에 padding을 적용하였습니다.
@juhee067 님이 `p-4`를 말씀해주셨는데 실제로 적용해보니까 padding 없을때랑 별 차이가 없는 것 같아서 `p-8`로 지정하였습니다.
=> [C조] 레이아웃 컴포넌트 / main padding 설정 hotfix

src/pages/login/Login.tsx, src/routes/index.tsx
=> [C조] 로그인 페이지 / 로그인 UI

src/components/Common/TitleContainer.tsx
- #54 
- TitleContainer 컴포넌트를 개발하였습니다.
- 사용방법
```javascript
<TitleContainer content="타이틀">
<div>어쩌구 저쩌구</div>
</TitleContainer>
```
=> [C조] TitleContainer 컴포넌트 개발

src/components/Common/BasicSettingSubTitle.tsx
flex row 시 가운데 정렬 되지않는 이슈가 있어 items-center 속성을 추가했습니다.
- `items-center` 추가
=> [A조] 기본 설정 페이지 flex 스타일 수정

src/pages/workManagement/WorkManagementPage.tsx, src/routes/index.tsx
- #86 
- 출퇴근 관리 너비 수정
- 너비 조정을 최상위 파일에서 진행하는 게 어떨까요?
=> [C조] 출퇴근 관리 너비 수정

src/layout/Header/Header.tsx, src/layout/Navigation/Navigation.tsx
- #89 
- 헤더, 내비게이션 유저 mockData 권한 수정
=> [C조] 헤더, 내비게이션 유저 mockData 권한 수정 hotfix

src/apis/salaryRange.api.ts
- #94 
- 급여계산표 import 경로 오류 수정
=> [HOTFIX] 급여계산표 import 경로 오류 수정

src/components/Common/Select.tsx, src/components/MemberManagement/MemberManagementFilterBar.tsx, src/components/UserBoard/View/UserBoardFilterBar/UserBoardFilterBar.tsx, src/pages/memberManagement/MemberInfoPage.tsx, src/pages/memberManagement/MemberManagementPage.tsx, src/pages/userBoard/view/BoardViewPage.tsx, src/pages/userBoard/write/BoardWritePage.tsx
- #97 
- 회원관리, 회원게시판 페이지 레이아웃 css 수정
- 회원관리, 회원게시판 SelectBox 적용
=> [B조] 회원관리, 회원게시판 SelectBox 적용

src/routes/index.tsx
- #99 
- 기본설정 게시판 설정 내비게이션 경로 수정
-
- 메인 회원게시판과 착각해 잘못 수정한 경로를 수정합니다.
=> [B조] 기본설정 게시판 설정 내비게이션 경로 수정

src/pages/documentManagement/certificationManagement/CertificateManagement.tsx, src/pages/documentManagement/certificationManagement/constants/index.ts
- #82 
- 증명서 관리 페이지에 드롭다운, 검색바 공통컴포넌트를 적용하였습니다.
- 증명서 관리 페이지의 너비를 수정하였습니다.
=> [C조] 증명서관리 페이지 / 공통컴포넌트 적용 및 너비 수정

src/components/SalarySettlement/SalaryTable/SalaryTable.tsx, src/components/SalarySettlement/SalaryTable/SalaryTableHeader.tsx, src/hooks/SalarySettlement/useFilteredEmployees.ts, src/pages/holidayCalendar/HolidayCalendarPage.tsx, src/pages/salarySettlement/SalarySettlementPage.tsx
#102
- 급여정산 페이지 CSS 수정
- 휴무 캘린더 페이지 CSS 수정
=> [C조] 급여정산, 휴무캘린더 CSS 수정

.gitignore, src/apis/axiosInstance.ts, src/constants/url.ts
- #111 
- 최상단에 있는 constants 폴더의 url.ts 파일을 삭제하였습니다.
- gitignore에 `.env`를 추가하였습니다.
BASE_URL은 각자 로컬의 `.env` 폴더에서 관리해주시면 됩니다.
=> [C조] 환경변수 관리 hotfix

src/layout/Navigation/constants/index.ts, src/routes/index.tsx
- #106 
- 내비게이션의 회원게시판탭 css 적용되지 않던 이슈를 해결하였습니다.
=> [C조] 내비게이션 / 회원게시판탭 css 적용되지 않던 이슈 해결

src/pages/memberManagement/MemberManagementPage.tsx, src/pages/memberManagement/SuperManagerSetting.tsx, src/routes/index.tsx
- #142 
- 회원관리 - 최고/지점관리자 설정 페이지 UI 개발
=> [C조] 회원관리 - 최고/지점관리자 설정 페이지 UI 개발

src/layout/Header/Header.tsx, src/layout/Header/HeaderProfile.tsx, src/store/authAtoms.ts
로그아웃시 레이아웃 컴포넌트가 리렌더링 안되던 이슈를 해결하였습니다.
- 로그아웃시 레이아웃 컴포넌트가 리렌더링 안되던 이슈를 해결하였습니다.
=> [C조] 로그아웃시 레이아웃 컴포넌트 리렌더링 안되던 이슈 해결

src/components/OtManagement/OtManagementFilterbar/OtManagementManagementFilterbar.tsx, src/components/OtManagement/OtManagementFilterbar/WeekSelector.tsx, src/components/OtManagement/OtManagementHeader.tsx, src/components/OtManagement/OtManagementList/OtManagementTable.tsx, src/components/OtManagement/OtManagementList/OtManagementTableItem.tsx, src/pages/otManagement/OtManagementPage.tsx, src/routes/index.tsx
=> [B조] OT관리 UI 제작

src/apis/user-management.api.ts, src/components/MemberInfo/MemberInfoCommon/MemberInfoDropdownMenu.tsx, src/components/MemberManagement/MemberManagementFilterBar.tsx, src/components/MemberManagement/MemberManagementTable.tsx, src/components/MemberManagement/MemberManagementTableCell.tsx, src/constants/memberManagementTableTitle.ts, src/hooks/apis/useUserManagement.ts, src/pages/memberManagement/MemberManagementPage.tsx
- 회원관리 리스트 페이지네이션 적용
- 회원상세 기본정보 테이블 연차신청, OT신청 제거
=> [B조 dev] 회원관리 페이지 / 페이지네이션 적용, UI 수정

src/components/OfficeSetting/OfficeSettingCreate.tsx, src/components/OfficeSetting/OfficeSettingTableCell.tsx, src/hooks/useSalaryRange.ts, src/models/branches.model.ts, src/pages/officeSetting/ManagementOfficePage.tsx
- #176 
- 지점추가를 했을 때 추가된 새로운 목록을 가져오지 않는 버그 수정
- 직인/명판 여부 조건 변경
=> [A조 dev] 지점설정 페이지 버그 수정

package-lock.json, package.json, src/layout/Navigation/Navigation.tsx, src/layout/Navigation/const/index.ts, src/layout/Navigation/constants/index.ts, src/routes/index.tsx
#180 
- quill 라이브러리 제거
- 라우트에서 게시판 관련 부분 제거
=> [A, B]게시판 관련 코드 삭제

src/layout/Navigation/const/index.ts, src/layout/Navigation/constants/index.ts
#183 
- 인사 관리 페이지 사라짐에 따라 주석처리
=> [B조] 인사관리 라우트 주석처리

.github/workflows/deploy.yml, build.sh
#200 
- build.sh 파일 추가
- .github/workflows 폴더 및 파일 생성
=> [dev] 배포 방법 변경을 위한 파일 생성

src/components/Common/Input.tsx
=> [COMMON] Input 공통 컴포넌트 생성

src/apis/work.api.ts, src/components/WorkManagement/GenderIcon.tsx, src/components/WorkManagement/Work/WorkTable.tsx, src/components/WorkManagement/Work/WorkTableRows.tsx, src/components/WorkManagement/WorkFilter.tsx, src/components/WorkManagement/WorkManagementLayout.tsx, src/components/WorkManagement/WorkSelect.tsx, src/constants/queryKeys.ts, src/constants/workManagement/workTable.mock.ts, src/hooks/apis/useWork.ts, src/models/work.model.ts, src/pages/workManagement/PartManagementPage.tsx, src/pages/workManagement/WorkManagementPage.tsx
- #206 
- 지점 & 파트 필터 기능, 공통 select 컴포넌트 삭제, 개별적인 select 제작  
- 필터 기능 연결  table 데이터 필터링
- gender 타입 변경
=> [C조]-근로관리 필터 및 조회 기능 개발

src/apis/commute.api.ts, src/constants/queryKeys.ts, src/hooks/apis/useCommute.ts, src/pages/simpleMenu/Commute.tsx, src/pages/simpleMenu/SimpleMenuPage.tsx
- 간편메뉴 Style 수정
- 출근 등록 API 연결
=> [C조] 간편메뉴 Style 수정 및 출근 등록 API 연결

src/components/WorkManagement/Commute/CommuteTable.tsx, src/components/WorkManagement/PartTime/PartTimeTable.tsx, src/components/WorkManagement/Work/WorkTable.tsx, src/components/WorkManagement/WorkManagementLayout.tsx, src/constants/workManagement/workTable.mock.ts, src/models/work.model.ts
- #206 
- 출퇴근/파트타이머 관리 필터 기능 추가
=> [C조]-출퇴근/파트타이머 관리 필터 기능 추가

src/components/BasicSetting/HrManagement/HrManagementForm.tsx, src/components/BasicSetting/HrManagement/HrManagementItem.tsx, src/components/BasicSetting/WorkingSetting/SetPart/SetPart.tsx, src/components/BasicSetting/WorkingSetting/SetPart/SetPartForm.tsx, src/hooks/apis/useParts.ts, src/hooks/apis/useUserManagement.ts, src/layout/Navigation/constants/index.ts, src/models/hr.model.ts, src/models/work-policies.ts, src/pages/basicSetting/HrManagementPage.tsx, src/pages/basicSetting/WorkingPage.tsx, src/routes/index.tsx, src/utils/adaptPartValue.ts
#131 
- 기본설정 적용시 기본 설정으로 값이 세팅되게 만들었습니다.
- 파트 간편 추가 버튼 클릭 시 간편 추가하고 싶은 값을 선택할 수 있습니다. 확인을 눌렀을 때 Promise.allSettled를 이용해 한번에 post 요청을 보내지만, 현재 첫 번째 요청만 잘 들어가고 나머지는 500 에러가 납니다.   
-> `setPartForm.tsx`에 주석으로 작성해두었습니다.
- 인사기록 관리 UI가 추가되었습니다.
=> [A조 dev] 근무 설정 페이지 기능 추가

vercel.json
=> [CHORE] vercel 백엔드 경로 수정

package-lock.json, package.json, src/apis/authAxiosInstance.ts, src/components/BasicSetting/Contract/CertificateTemplateList.tsx, src/components/BasicSetting/Contract/ContractTemplateList.tsx, src/components/BasicSetting/Contract/DocumentTemplateList.tsx, src/components/BasicSetting/Contract/Editor/Editor.tsx, src/components/BasicSetting/Contract/Editor/editorStyle/editorCss.css, src/components/BasicSetting/Contract/Editor/lib/getDocument.ts, src/components/BasicSetting/Contract/TemplateSetting.tsx, src/components/DayoffManagement/DayoffManagementHeader.tsx, src/components/HolidayCalendar/EmployeeHolidayRegisterModal.tsx, src/components/HolidayCalendar/HolidayCalendarHeader.tsx, src/components/HolidayCalendar/HolidayDeletionPopover.tsx, src/components/HolidayCalendar/HolidayRegisterPopover.tsx, src/components/MemberInfo/MemberInfoCommon/MemberBasicInfoDatePicker.tsx, src/components/MemberManagement/MemberManagementTable.tsx, src/components/MemberManagement/MemberManagementTableCell.tsx, src/pages/basicSetting/CertificatePage.tsx, src/pages/basicSetting/ContractPage.tsx, src/pages/basicSetting/DocumentPage.tsx, src/pages/holidayCalendar/HolidayCalendarPage.tsx, src/pages/login/Login.tsx, src/pages/memberManagement/MemberManagementPage.tsx, src/routes/index.tsx, src/routes/loading.tsx, tailwind.config.js
#246  #235  #236  #237 
- editor의 빈공간 클릭 시 편집이 되도록 수정
- 계약서 불러오기를 위한 로직 추가 및 구현
- 테스트를 위한 목데이터 간단히 준비
- 후에 api를 작업 할 때 editor의 추가 기능을 더 작업할 지 고민(ex : 템플릿 불러오기, 지우기, 새로고침)
- api 로직 준비 되면 작업할 예정
=> [Feat] editor 기능 추가 작업, 계약서 불러오기 및 계약서 목데이터 준비

src/components/OfficeSetting/OfficeSettingTable.tsx, src/hooks/apis/useSalaryTemplates.ts, src/pages/basicSetting/SalaryRangePage.tsx
- #254 
- 임금설정 페이지에서 사용되는 임금템플릿을 가져오는 로직 수정
- 급여구간표 페이지 스타일 수정
=> [FIX] Fix/#254

src/components/BasicSetting/HourlyRange/HourlyRangeContainer.tsx, src/components/BasicSetting/HourlyRange/HourlyRangeCreate.tsx, src/components/BasicSetting/HourlyRange/HourlyRangeInputContainer.tsx, src/components/BasicSetting/HourlyRange/HourlyRangeItem.tsx, src/components/BasicSetting/HourlyRange/HourlyRangeList.tsx, src/components/BasicSetting/HourlyRange/HourlyRangeSelect.tsx, src/components/BasicSetting/Wage/WageContainer.tsx, src/components/BasicSetting/Wage/WageMinimumSettingDialog.tsx, src/pages/basicSetting/HourlyRangePage.tsx, src/pages/basicSetting/WagePage.tsx
#253 
- 시급설정 UI 수정
- 시급설정 페이지 api 연결
=> 시급설정 페이지 기능 추가 / UI 수정

src/App.tsx, src/apis/axiosInstance.ts, src/components/BasicSetting/WorkingSetting/SetPart/SetPartItem.tsx, src/components/Common/Toast/ToastItem.tsx, src/components/Common/Toast/ToastList.tsx, src/hooks/apis/useParts.ts, src/hooks/useToast.ts, src/store/toastAtoms.ts, tailwind.config.js
#256 
- `App.tsx` 파일에 toast를 추가했습니다.
- axios instance에서 사용하는 navigate 훅이 잘 동작하지 않아 `window.location.href` 로 변경했습니다.
1. `const toast = useToast()` useToast훅을 호출
2. `toast.success(문구, { timer: 시간(default 1000ms), position: top | bottom(default) }` 형식으로 호출해 사용
3. toast.success / toast.error / toast.notice 세 가지 방법으로 이용할 수 있습니다.
=> feat: 토스트 메시지 구현
